### PR TITLE
Answers pushed

### PR DESCRIPTION
**Pull request by Gayathri95**
Please review difference in the file answers.txt and provide feedback.

### CODE REVIEW

**Comment by prash-10** [comment]
Answer to the second question can be supported with an example. All other answers are precise and to the point.

**Review by prash-10 — CHANGES_REQUESTED** [review]
In my view an example could be added in second question.

**Comment by Gayathri95** [comment]
Addressed review comments

**Comment by Gayathri95** [comment]
@prash-10  reopening to merge the pull request.

**Pull request merged**
